services:
  kafka:
    extends:
      file: deps.yaml
      service: kafka

  registry:
    extends:
      file: deps.yaml
      service: registry

  cli:
    extends:
      file: deps.yaml
      service: cli

  registrations2epics:
    hostname: registrations2epics
    container_name: registrations2epics
    depends_on:
      - kafka
      - registry
      - jaws
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY=http://registry:8081
      - CREATE_SOURCE_TOPIC=true
