---
version: '3.8'

services:
  registrations2epics:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    volumes:
      - ./build/install/registrations2epics:/opt/registrations2epics